# $schema: https://raw.githubusercontent.com/picamator/transfer-object/main/schema/definition.schema.json
Credentials:
  login:
    type: string
    required:
    protected:
  token:
    type: string
    required:
    protected:
  createdAt:
    dateTimeType: "DateTimeImmutable"
    required:
    protected:
  updatedAt:
    dateTimeType: "DateTime"
    required:
