# $schema: https://raw.githubusercontent.com/picamator/transfer-object/main/schema/definition.schema.json
Merchant:
  merchantReference:
    type: string
    required:
  country:
    enumType: "Picamator\\Examples\\TransferObject\\Enum\\CountryEnum"
    required:
  isActive:
    type: bool
    required:
