# $schema: ./../../schema/definition.schema.json
Template:
  definitionPath:
    type: string
    required:
  className:
    type: string
    required:
  classNamespace:
    type: string
    required:
  imports:
    type: ArrayObject<string,string>
  properties:
    type: ArrayObject<string,string>
  propertyAttributes:
    type: ArrayObject<string,array<int,string>>
  metaConstants:
    type: ArrayObject<string,string>
  metaAttributes:
    type: ArrayObject<string,array<int,string>>
  docBlocks:
    type: ArrayObject<string,string>
  nullables:
    type: ArrayObject<string,bool>
  protects:
    type: ArrayObject<string,bool>
