# $schema: https://raw.githubusercontent.com/picamator/transfer-object/main/schema/config.schema.json
generator:
  transferNamespace: "Picamator\\Examples\\TransferObject\\Generated\\AdvancedTransferGenerator"
  transferPath: "${PROJECT_ROOT}/examples/Generated/AdvancedTransferGenerator"
  definitionPath: "${PROJECT_ROOT}/examples/config/advanced-transfer-generator/definition"
